// <auto-generated />
using System;
using DripCheckAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DripCheckAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240621045754_Init migration")]
    partial class Initmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DripCheckAPI.Models.WarrantyDetail", b =>
                {
                    b.Property<int>("WarrantyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantyDetailId"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarrantyOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WarrantyDetailId");

                    b.ToTable("WarrantyDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
